---

- hosts: webhost
  become: yes
  tasks:
    - name: Add repo for Docker
      yum_repository:
        name: docker
        description: Repository containing docker packages
        baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
        enabled: true
        gpgcheck: no
            
    - name: Remove incompatible packages
      yum:
        name:
          - podman
          - buildah
        state: absent
    
    - name: Install docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        
