---

- hosts: proxy
  become: yes
  
  handlers:
    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

  tasks:
    - name: Install haproxy package
      yum:
        name: haproxy
        state: present
    
    - name: Update configuration file
      copy:
        dest: /etc/haproxy/haproxy.cfg
        src: /mnt/d/UKC/GIT/WWW/haproxy.cfg
        force: yes
      notify: Restart haproxy
    
    - name: Start haproxy service
      service:
        name: haproxy
        state: started
        enabled: yes
    
    - name: Enable firewall access for HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes