---

- hosts: db
  become: yes
  tasks:
    
    - name: Install mariadb packages
      yum:
        name: 
          - mariadb-server
          - python3-PyMySQL
        state: present
        
    - name: Start mariadb service
      service:
        name: mariadb
        state: started
        enabled: yes
        
    - name: 
        