---

- hosts: webhost
  become: yes
  tasks:
    - name: Add repo for Docker
      yum_repository:
        name: docker
        description: Repository containing docker packages
        baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/
        enabled: true
        gpgcheck: no
            
    - name: Remove incompatible packages
      yum:
        name:
          - podman
          - buildah
        state: absent
    
    - name: Install docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        
    - name: Install docker lib for python
      pip:
        name: docker
        state: present
        
    - name: Ensure docker is running
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Install docker httpd-php image
      docker_image:
        name: polinux/httpd-php
        source: pull
        
    - name: Run httpd-php container
      docker_container:
        name: WebServer
        image: polinux/httpd-php
        state: started
        detach: yes
        interactive: yes
        ports: "80:80"
        volumes: /home/chris/webroot/:/var/www/html/
        restart_policy: always
